#RandomCommand config
#write the list of commands with out the slash and in quotes
#You may make multiple lists of commands
#EX:
#list1:
#- "say this is list one"
#list2:
#- "say this is list two"
#EX:
# you would type restart not /restart
#{name} will be replaced with the player name
#you use it bo doing the command /rc <listname> <name>
#you can chose if you want to use %s or not
#if you want to use %
#you add the % by seperating the percentage with a :
#the plugin goes top to bottom and inorder to make shure things happen the way you want them to put the items in the order of the percentage you want them to go in
#to make shure something happens at something that has a %100 chance at the bottom
#EX: 
#commands:
#- "10:say {name} is epic"
#- "50:say {name} is cool"
#- "100:say {name}"
#this will broadcast the name of the player with mabye other stuff
#if you dont want to use % it will chose a random command and they all have equal chance
use%: true
commands:
- "100:say {name}"