main: net.snailz.randomcommand.Main
name: RandomCommand
version: 0.3.2
author: Snailz
commands:
    RC:
        discription: execute a random command from the list
        usage: RC <listname> <playername>
        permission: randomcommand.command