main: net.snailz.executerandomcommand.Main
name: RandomCommand
version: 1.0
author: Snailz
commands:
    RC:
        discription: execute a random command from the list
        usage: RC <player>
        permission: randomcommand.command