main: net.snailz.randomcommand.Main
name: RandomCommand
version: 0.4.2
author: Snailz
commands:
    rc:
        description: execute a random command from the list
        usage: /rc <listname> <playername>
        permission: randomcommand.command
    rcreload:
        description: reload the config for Random Command
        usage: /rcreload
        permission: randomcommand.reload
#    rconfig:
#        description: add and remove commands from the config
#        usage: /rconfig <add/remove> <list name> <percentage/none> <command(s) seperated by ;s>
#        permission: randomcommand.rconfig
permissions:
    randomcommand.command:
        description: Gives the player permission to use /rc
        default: op
#    rconfig:
#       description: Gives the player permission to use /rconfig
#       default: op
    randomcommand.reload:
        description: Gives the player permission to use /rcreload
        default: op