main: net.snailz.randomcommand.Main
name: RandomCommand
version: 0.3
author: Snailz
commands:
    RC:
        discription: execute a random command from the list
        usage: RC <player>
        permission: randomcommand.command